version: '3'
services:
  # db:
  #   image: postgres:12
  #   environment:
  #     POSTGRES_DB: VPN
  #     POSTGRES_USER: postgress
  #     POSTGRES_PASSWORD: admin

  web:
    build: .
    command: python vpn/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
# Comented code can be used to connect to postgess db